site_name: NBCSports-StatsAPI
site_url: "https://jneatherynbc.github.io/nbcsports-statsapi-docs/"
nav:
  - Home: index.md
  - Getting Started: start.md
  - V1: v1.md
  - V2: v2.md

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  nav_style: dark
